---
# Interactive inputs for SWPM

- name: Set temporary fact if target has High Availability
  ansible.builtin.set_fact:
    interactive_input_type_ha: true
  when:
    - interactive_input_type in ['s4hana_ha']

# Mandatory inputs
- name: Block for sap_system_sid
  when: sap_system_sid is not defined or not sap_system_sid
  no_log: true
  block:
    - name: Interactive input - sap_system_sid
      ansible.builtin.pause:
        prompt: |
          Please enter SAP System ID (SID).
          Example: S01
      register: sap_system_sid_register

    - name: Set fact for sap_system_sid
      ansible.builtin.set_fact:
        sap_system_sid: "{{ sap_system_sid_register.user_input }}"
        sap_swpm_sid: "{{ sap_system_sid_register.user_input }}"

- name: Block for sap_system_nwas_abap_ascs_instance_nr
  when: sap_system_nwas_abap_ascs_instance_nr is not defined or not sap_system_nwas_abap_ascs_instance_nr
  no_log: true
  block:
    - name: Interactive input - sap_system_nwas_abap_ascs_instance_nr
      ansible.builtin.pause:
        prompt: |
          Please enter ABAP System Central Service Instance Number (ASCS).
          Example: 00
      register: sap_system_nwas_abap_ascs_instance_nr_register
      failed_when: sap_system_nwas_abap_ascs_instance_nr_register.user_input | length != 2

    - name: Set fact for sap_system_nwas_abap_ascs_instance_nr
      ansible.builtin.set_fact:
        sap_system_nwas_abap_ascs_instance_nr: "{{ sap_system_nwas_abap_ascs_instance_nr_register.user_input }}"
        sap_swpm_ascs_instance_nr: "{{ sap_system_nwas_abap_ascs_instance_nr_register.user_input }}"

- name: Block for sap_system_nwas_abap_ers_instance_nr
  when:
    - interactive_input_type_ha | d(false)
    - sap_system_nwas_abap_ers_instance_nr is not defined or not sap_system_nwas_abap_ers_instance_nr
  no_log: true
  block:
    - name: Interactive input - sap_system_nwas_abap_ers_instance_nr
      ansible.builtin.pause:
        prompt: |
          Please enter Enqueue Replication Service Instance Number (ERS).
          Example: 01
      register: sap_system_nwas_abap_ers_instance_nr_register
      failed_when: sap_system_nwas_abap_ers_instance_nr_register.user_input | length != 2

    - name: Set fact for sap_system_nwas_abap_ers_instance_nr
      ansible.builtin.set_fact:
        sap_system_nwas_abap_ers_instance_nr: "{{ sap_system_nwas_abap_ers_instance_nr_register.user_input }}"
        sap_swpm_ers_instance_nr: "{{ sap_system_nwas_abap_ers_instance_nr_register.user_input }}"

- name: Block for sap_system_nwas_abap_pas_instance_nr
  when:
    - interactive_input_type_ha | d(false)
    - interactive_input_type in ['s4hana_ha']
    - sap_system_nwas_abap_pas_instance_nr is not defined or not sap_system_nwas_abap_pas_instance_nr
  no_log: true
  block:
    - name: Interactive input - sap_system_nwas_abap_pas_instance_nr
      ansible.builtin.pause:
        prompt: |
          Please enter Primary Application Server Instance Number (PAS).
          Example: 02
      register: sap_system_nwas_abap_pas_instance_nr_register
      failed_when: sap_system_nwas_abap_pas_instance_nr_register.user_input | length != 2

    - name: Set fact for sap_system_nwas_abap_pas_instance_nr
      ansible.builtin.set_fact:
        sap_system_nwas_abap_pas_instance_nr: "{{ sap_system_nwas_abap_pas_instance_nr_register.user_input }}"
        sap_swpm_pas_instance_nr: "{{ sap_system_nwas_abap_pas_instance_nr_register.user_input }}"

- name: Block for sap_system_nwas_abap_aas_instance_nr
  when:
    - interactive_input_type_ha | d(false)
    - interactive_input_type in ['s4hana_ha']
    - sap_system_nwas_abap_aas_instance_nr is not defined or not sap_system_nwas_abap_aas_instance_nr
  no_log: true
  block:
    - name: Interactive input - sap_system_nwas_abap_aas_instance_nr
      ansible.builtin.pause:
        prompt: |
          Please enter Additional Application Server Instance Number (AAS).
          Example: 03
      register: sap_system_nwas_abap_aas_instance_nr_register
      failed_when: sap_system_nwas_abap_aas_instance_nr_register.user_input | length != 2

    - name: Set fact for sap_system_nwas_abap_aas_instance_nr
      ansible.builtin.set_fact:
        sap_system_nwas_abap_aas_instance_nr: "{{ sap_system_nwas_abap_aas_instance_nr_register.user_input }}"
        sap_swpm_aas_instance_nr: "{{ sap_system_nwas_abap_aas_instance_nr_register.user_input }}"


# Passwords
- name: Interactive input - sap_swpm_use_master_password
  ansible.builtin.pause:
    prompt: |
      Please enter y to use Master password for all passwords during SAP installation (y/n).
      Default: n
      Press enter to skip.
  register: sap_swpm_use_master_password_register

- name: Block for sap_swpm_master_password
  when:
    - sap_swpm_use_master_password_register.user_input | d('n') == 'y'
    - sap_swpm_master_password is not defined or not sap_swpm_master_password
  no_log: true
  block:
    - name: Interactive input - sap_swpm_master_password
      ansible.builtin.pause:
        prompt: "Please enter SAP Master Password."
      register: sap_swpm_master_password_register

    - name: Set fact for sap_swpm_master_password
      ansible.builtin.set_fact:
        sap_swpm_master_password: "{{ sap_swpm_master_password_register.user_input }}"

- name: Block for sap_swpm_ddic_000_password
  when:
    - sap_swpm_use_master_password_register.user_input | d('n') != 'y'
    - sap_swpm_ddic_000_password is not defined or not sap_swpm_ddic_000_password
  no_log: true
  block:
    - name: Interactive input - sap_swpm_ddic_000_password
      ansible.builtin.pause:
        prompt: Please enter password for DDIC user in client 000.
      register: sap_swpm_ddic_000_password_register

    - name: Set fact for sap_swpm_ddic_000_password
      ansible.builtin.set_fact:
        sap_swpm_ddic_000_password: "{{ sap_swpm_ddic_000_password_register.user_input }}"

# Database inputs - ABAP
- name: Block for sap_swpm_db_schema_abap
  when: sap_swpm_db_schema_abap is not defined or not sap_swpm_db_schema_abap
  no_log: true
  block:
    - name: Interactive input - sap_swpm_db_schema_abap
      ansible.builtin.pause:
        prompt: |
          Please enter ABAP database schema name.
          Example: SAPHANADB
      register: sap_swpm_db_schema_abap_register

    - name: Set fact for sap_swpm_db_schema_abap
      ansible.builtin.set_fact:
        sap_swpm_db_schema_abap: "{{ sap_swpm_db_schema_abap_register.user_input }}"

- name: Block for sap_swpm_db_schema_abap_password
  when: sap_swpm_db_schema_abap_password is not defined or not sap_swpm_db_schema_abap_password
  no_log: true
  block:
    - name: Interactive input - sap_swpm_db_schema_abap_password
      ansible.builtin.pause:
        prompt: "Please enter password for ABAP database schema."
      register: sap_swpm_db_schema_abap_password_register

    - name: Set fact for sap_swpm_db_schema_abap_password
      ansible.builtin.set_fact:
        sap_swpm_db_schema_abap_password: "{{ sap_swpm_db_schema_abap_password_register.user_input }}"

# Database inputs - Shared
- name: Block for sap_swpm_db_sidadm_password
  when: sap_swpm_db_sidadm_password is not defined or not sap_swpm_db_sidadm_password
  no_log: true
  block:
    - name: Interactive input - sap_swpm_db_sidadm_password
      ansible.builtin.pause:
        prompt: "Please enter password of sidadm user of database."
      register: sap_swpm_db_sidadm_password_register

    - name: Set fact for sap_swpm_db_sidadm_password
      ansible.builtin.set_fact:
        sap_swpm_db_sidadm_password: "{{ sap_swpm_db_sidadm_password_register.user_input }}"

- name: Block for sap_swpm_db_system_password
  when: sap_swpm_db_system_password is not defined or not sap_swpm_db_system_password
  no_log: true
  block:
    - name: Interactive input - sap_swpm_db_system_password
      ansible.builtin.pause:
        prompt: "Please enter password of SYSTEM user in database."
      register: sap_swpm_db_system_password_register

    - name: Set fact for sap_swpm_db_system_password
      ansible.builtin.set_fact:
        sap_swpm_db_system_password: "{{ sap_swpm_db_system_password_register.user_input }}"

- name: Block for sap_swpm_db_systemdb_password
  when: sap_swpm_db_systemdb_password is not defined or not sap_swpm_db_systemdb_password
  no_log: true
  block:
    - name: Interactive input - sap_swpm_db_systemdb_password
      ansible.builtin.pause:
        prompt: "Please enter password of SYSTEMDB user in database."
      register: sap_swpm_db_systemdb_password_register

    - name: Set fact for sap_swpm_db_systemdb_password
      ansible.builtin.set_fact:
        sap_swpm_db_systemdb_password: "{{ sap_swpm_db_systemdb_password_register.user_input }}"


# Mandatory inputs for SAP High Availability
- name: Block for sap_vm_provision_ha_vip_nwas_abap_ascs
  when:
    - interactive_input_type_ha | d(false)
    - sap_vm_provision_ha_vip_nwas_abap_ascs is not defined or not sap_vm_provision_ha_vip_nwas_abap_ascs
  block:
    - name: Interactive input - sap_vm_provision_ha_vip_nwas_abap_ascs
      ansible.builtin.pause:
        prompt: |
          Please enter Virtual IP for SAP ASCS Instance. Platform specific recommendations:
          AWS:                  the VIP must be **outside** of any VPC Subnet ranges (e.g. 192.168.100.102/32)
          GCP:                  the VIP must be within the VPC Subnetwork range attached to GCP Backend Service for the Internal passthrough Network Load Balancer (e.g. 10.10.10.10/32)
          IBM Cloud:            the VIP is within the VPC Subnet range and is statically defined by the IBM Cloud Load Balancer [NLB L4 or ALB L7], variable should be commented out
          IBM Cloud, Power VS:  the VIP must be within the IBM Power Infrastructure VLAN Subnet range (e.g. 192.168.4.4/26)
          MS Azure:             the VIP must be within the VNet Subnet range attached to the Azure Load Balancer [NLB L4] (e.g. 10.10.10.10/22)
          IBM PowerVM:          the VIP must be within the VLAN Subnet range
          OVirt KVM:            the VIP must be within the VLAN Subnet range
          KubeVirt:             the VIP must be within the VLAN Subnet range
      register: sap_vm_provision_ha_vip_nwas_abap_ascs_register

    - name: Set fact for sap_vm_provision_ha_vip_nwas_abap_ascs
      ansible.builtin.set_fact:
        sap_vm_provision_ha_vip_nwas_abap_ascs: "{{ sap_vm_provision_ha_vip_nwas_abap_ascs_register.user_input }}"

- name: Block for sap_vm_provision_ha_vip_nwas_abap_ers
  when:
    - interactive_input_type_ha | d(false)
    - sap_vm_provision_ha_vip_nwas_abap_ers is not defined or not sap_vm_provision_ha_vip_nwas_abap_ers
  block:
    - name: Interactive input - sap_vm_provision_ha_vip_nwas_abap_ers
      ansible.builtin.pause:
        prompt: |
          Please enter Virtual IP for SAP ERS Instance. Platform specific recommendations:
          AWS:                  the VIP must be **outside** of any VPC Subnet ranges (e.g. 192.168.100.102/32)
          GCP:                  the VIP must be within the VPC Subnetwork range attached to GCP Backend Service for the Internal passthrough Network Load Balancer (e.g. 10.10.10.10/32)
          IBM Cloud:            the VIP is within the VPC Subnet range and is statically defined by the IBM Cloud Load Balancer [NLB L4 or ALB L7], variable should be commented out
          IBM Cloud, Power VS:  the VIP must be within the IBM Power Infrastructure VLAN Subnet range (e.g. 192.168.4.4/26)
          MS Azure:             the VIP must be within the VNet Subnet range attached to the Azure Load Balancer [NLB L4] (e.g. 10.10.10.10/22)
          IBM PowerVM:          the VIP must be within the VLAN Subnet range
          OVirt KVM:            the VIP must be within the VLAN Subnet range
          KubeVirt:             the VIP must be within the VLAN Subnet range
      register: sap_vm_provision_ha_vip_nwas_abap_ers_register

    - name: Set fact for sap_vm_provision_ha_vip_nwas_abap_ers
      ansible.builtin.set_fact:
        sap_vm_provision_ha_vip_nwas_abap_ers: "{{ sap_vm_provision_ha_vip_nwas_abap_ers_register.user_input }}"

- name: Block for sap_system_ascs_ers_cluster_name
  when:
    - interactive_input_type_ha | d(false)
    - sap_system_ascs_ers_cluster_name is not defined or not sap_system_ascs_ers_cluster_name
  block:
    - name: Interactive input - sap_system_ascs_ers_cluster_name
      ansible.builtin.pause:
        prompt: |
          Please enter cluster name for SAP ASCS/ERS Cluster.
          Default: clusterhdb
          Press enter to skip.
      register: sap_system_ascs_ers_cluster_name_register

    - name: Set fact for sap_system_ascs_ers_cluster_name
      ansible.builtin.set_fact:
        sap_system_ascs_ers_cluster_name: "{{ 'clusterhdb' if not sap_system_ascs_ers_cluster_name_register.user_input
          else sap_system_ascs_ers_cluster_name_register.user_input }}"

- name: Block for sap_system_ascs_ers_hacluster_user_password
  when:
    - interactive_input_type_ha | d(false)
    - sap_system_ascs_ers_hacluster_user_password is not defined or not sap_system_ascs_ers_hacluster_user_password
  block:
    - name: Interactive input - sap_system_ascs_ers_hacluster_user_password
      ansible.builtin.pause:
        prompt: |
          Please enter password of hacluster user for SAP ASCS/ERS Cluster.
          Default: clusterpass
          Press enter to skip.
      register: sap_system_ascs_ers_hacluster_user_password_register

    - name: Set fact for sap_system_ascs_ers_hacluster_user_password
      ansible.builtin.set_fact:
        sap_system_ascs_ers_hacluster_user_password:
          "{{ 'clusterpass' if not sap_system_ascs_ers_hacluster_user_password_register.user_input
            else sap_system_ascs_ers_hacluster_user_password_register.user_input }}"


# Optional inputs
- name: Interactive input - Optional inputs for SWPM
  ansible.builtin.pause:
    prompt: |
      Please enter y if you would like to enter optional inputs for SWPM. (y/n). Default: n
      Press enter to skip.
  register: __optional_inputs_swpm
  no_log: true

- name: Block for sap_swpm_sapadm_uid
  when:
    - __optional_inputs_swpm.user_input == 'y'
    - sap_swpm_sapadm_uid is not defined or not sap_swpm_sapadm_uid
  block:
    - name: Interactive input - sap_swpm_sapadm_uid
      ansible.builtin.pause:
        prompt: |
          (Optional) Please enter unix User ID for user sapadm.
          Example: 3000
      register: sap_swpm_sapadm_uid_register

    - name: Set fact for sap_swpm_sapadm_uid
      ansible.builtin.set_fact:
        sap_swpm_sapadm_uid: "{{ sap_swpm_sapadm_uid_register.user_input }}"

- name: Block for sap_swpm_sidadm_uid
  when:
    - __optional_inputs_swpm.user_input == 'y'
    - sap_swpm_sidadm_uid is not defined or not sap_swpm_sidadm_uid
  block:
    - name: Interactive input - sap_swpm_sidadm_uid
      ansible.builtin.pause:
        prompt: |
          (Optional) Please enter unix User ID for user sidadm.
          Example: 3001
      register: sap_swpm_sidadm_uid_register

    - name: Set fact for sap_swpm_sidadm_uid
      ansible.builtin.set_fact:
        sap_swpm_sidadm_uid: "{{ sap_swpm_sidadm_uid_register.user_input }}"

- name: Block for sap_swpm_sapsys_gid
  when:
    - __optional_inputs_swpm.user_input == 'y'
    - sap_swpm_sapsys_gid is not defined or not sap_swpm_sapsys_gid
  block:
    - name: Interactive input - sap_swpm_sapsys_gid
      ansible.builtin.pause:
        prompt: |
          (Optional) Please enter unix Group ID for SAP System users.
          Example: 3002
      register: sap_swpm_sapsys_gid_register

    - name: Set fact for sap_swpm_sapsys_gid
      ansible.builtin.set_fact:
        sap_swpm_sapsys_gid: "{{ sap_swpm_sapsys_gid_register.user_input }}"

- name: Block for sap_swpm_update_etchosts
  when:
    - __optional_inputs_swpm.user_input == 'y'
    - sap_swpm_update_etchosts is not defined or not sap_swpm_update_etchosts
  block:
    - name: Interactive input - sap_swpm_update_etchosts
      ansible.builtin.pause:
        prompt: |
          (Optional) Please enter true to configure /etc/hosts in sap_swpm role.
          Default: false
      register: sap_swpm_update_etchosts_register

    - name: Set fact for sap_swpm_update_etchosts
      ansible.builtin.set_fact:
        sap_swpm_update_etchosts: "{{ 'false' if not sap_swpm_update_etchosts_register.user_input
         else sap_swpm_update_etchosts_register.user_input }}"
