---

#### Mandatory scenario specific variables ####

# Default Ansible Facts populate into default variables for all Ansible Roles
sap_hostname: "{{ ansible_hostname }}"
sap_domain: "{{ ansible_domain }}"
sap_ip: "{{ ansible_default_ipv4.address }}"

#### Mandatory parameters : Virtual instance names ####
# See virtual hostname information in SAP Note 2279110 and 962955
# Ensure this does not contain the local hostname, must use the Virtual Hostname for use with the Virtual IP (VIP)
# sap_swpm_virtual_hostname: "{{ sap_vm_provision_dynamic_inventory_nw_ascs_hostname }}-ha"
sap_swpm_db_host: "{{ sap_vm_provision_dynamic_inventory_hana_primary_hostname }}-ha" # Must be SAP HANA Virtual Hostname

#### Mandatory parameters : Preconfigure OS for SAP Software ####
sap_general_preconfigure_modify_etc_hosts: false
sap_general_preconfigure_reboot_ok: true
sap_general_preconfigure_fail_if_reboot_required: false
sap_hana_preconfigure_reboot_ok: true # SAP HANA hosts will reboot twice if sap_general_preconfigure_reboot_ok is true
sap_hana_preconfigure_fail_if_reboot_required: false
sap_hana_preconfigure_update: true
sap_hana_update_etchosts: true

#### Dynamic assignment of SAP HANA variables ####
sap_hana_sid: "{{ sap_system_hana_db_sid }}"
sap_hana_install_instance_nr: "{{ sap_system_hana_db_instance_nr }}"

#### Dynamic assignment of SAP HANA System Replication (HSR) variables ####
sap_ha_install_hana_hsr_sid: "{{ sap_system_hana_db_sid }}"
sap_ha_install_hana_hsr_instance_number: "{{ sap_system_hana_db_instance_nr }}"
sap_ha_install_hana_hsr_db_system_password: "{{ sap_hana_install_db_system_password
  if (sap_hana_install_use_master_password is defined and sap_hana_install_use_master_password == 'n'
    and sap_hana_install_db_system_password)
  else sap_hana_install_master_password }}"

#### Dynamic assignment for Virtual IP ####
sap_vm_temp_vip_hana_primary: "{{ sap_vm_provision_ha_vip_hana_primary }}"
sap_ha_pacemaker_cluster_vip_hana_primary_ip_address: "{{ sap_vm_provision_ha_vip_hana_primary }}"

#### Dynamic parameters for AWS ####
# Override of AWS IAM HA roles is required if 'HA-Role-Pacemaker' already exists
sap_vm_provision_aws_ha_iam_role: "HA-Role-Pacemaker-{{ sap_system_hana_db_sid }}"
sap_vm_provision_aws_ha_iam_instance_profile: "HA-Role-Pacemaker-{{ sap_system_hana_db_sid }}-profile"

#### Dynamic assignment of sap_storage_setup variables ####
host_specifications_dictionary: "{{ lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary') }}"

#### Mandatory parameters : Ansible Dictionary for SAP Installation Media ####
sap_software_hana_wildcard_list:
  - 'SAPCAR*'
  - 'IMDB_*'
  - 'SAPHOSTAGENT*'

sap_software_install_dictionary:

  sap_hana_2_sps07:

    softwarecenter_search_list_x86_64:
      - 'SAPCAR_1115-70006178.EXE'
      - 'IMDB_SERVER20_077_0-80002031.SAR'
      - 'SAPHOSTAGENT62_62-80004822.SAR' # SAP Host Agent 7.22

    softwarecenter_search_list_ppc64le:
      - 'SAPCAR_1115-70006238.EXE'
      - 'IMDB_SERVER20_077_0-80002046.SAR'
      - 'SAPHOSTAGENT62_62-80004831.SAR' # SAP Host Agent 7.22

  sap_hana_2_sps06:

    softwarecenter_search_list_x86_64:
      - 'SAPCAR_1115-70006178.EXE'
      - 'IMDB_SERVER20_067_4-80002031.SAR'
      - 'SAPHOSTAGENT61_61-80004822.SAR' # SAP Host Agent 7.22

    softwarecenter_search_list_ppc64le:
      - 'SAPCAR_1115-70006238.EXE'
      - 'IMDB_SERVER20_067_4-80002046.SAR'
      - 'SAPHOSTAGENT61_61-80004831.SAR' # SAP Host Agent 7.22

#### Non-interactive variables ####
## Uncommenting variables in this section will skip their check in Interactive Mode

### Infrastructure Provisioning selection ###
# sap_vm_provision_iac_type: "ENTER_STRING_VALUE_HERE"  # ansible , ansible_to_terraform , existing_hosts
# sap_vm_provision_iac_platform: "ENTER_STRING_VALUE_HERE"  # aws_ec2_vs , gcp_ce_vm , ibmcloud_vs , ibmcloud_powervs , msazure_vm , ibmpowervm_vm , kubevirt_vm , ovirt_vm , vmware_vm
# sap_vm_provision_host_specification_plan: "ENTER_STRING_VALUE_HERE"
# sap_vm_provision_dns_root_domain: "ENTER_STRING_VALUE_HERE"

### Key SAP System variables ###
# sap_system_hana_db_sid: "H01"
# sap_system_hana_db_instance_nr: "90"

### SAP Software installation media downloads ###
## SAP ONE Support Launchpad credentials
# sap_id_user: "ENTER_STRING_VALUE_HERE"
# sap_id_user_password: 'ENTER_STRING_VALUE_HERE'

## Directory for SAP installation media
# sap_install_media_detect_source_directory: "ENTER_STRING_VALUE_HERE" # e.g. /software

### SAP Product selection ###
## (see sap_software_install_dictionary for full definitions)
# sap_software_product: "ENTER_STRING_VALUE_HERE" # sap_hana_2_sps07_install , sap_hana_2_sps06_install

### SAP HANA Database Server installation ###
# sap_hana_install_use_master_password: "y"
# sap_hana_install_master_password: "ENTER_STRING_VALUE_HERE"

### SAP HANA Database Server installation - Optional variables ###
## SAP HANA log mode (set to overwrite for Sandbox only, HA cannot use overwrite)
# sap_hana_install_log_mode: normal

## List of comma separated components to be installed, default 'all'
# sap_hana_install_components: 'all'

## Unix User ID. Leave this blank if you want this set automatically by hdblcm
## For production systems, it's highly advisable to set this manually according to your environment's Unix ID policies
# sap_hana_install_userid:
# sap_hana_install_groupid:

# sap_hana_install_system_usage: custom  # hdblcm parameter system_usage
# sap_hana_install_restrict_max_mem: 'n'  # hdblcm parameter restrict_max_mem
# sap_hana_install_max_mem:  # hdblcm parameter max_mem in MB required when sap_hana_install_restrict_max_mem is y
# sap_hana_install_system_restart: 'n'  # select if role should start SAP HANA after each system boot
## Pass some extra arguments to the hdblcm cli, e.g.  --ignore=<check1>[,<check2>]...
# sap_hana_install_hdblcm_extraargs:

### High Availability variables ###
## Infrastructure Platform - High Availability Virtual IPs (VIPs)
## AWS:                  the VIP must be **outside** of any VPC Subnet ranges (e.g. 192.168.100.102/32)
## GCP:                  the VIP must be within the VPC Subnetwork range attached to GCP Backend Service for the Internal passthrough Network Load Balancer (e.g. 10.10.10.10/32)
## IBM Cloud:            the VIP is within the VPC Subnet range and is statically defined by the IBM Cloud Load Balancer [NLB L4 or ALB L7], variable should be commented out
## IBM Cloud, Power VS:  the VIP must be within the IBM Power Infrastructure VLAN Subnet range (e.g. 192.168.4.4/26)
## MS Azure:             the VIP must be within the VNet Subnet range attached to the Azure Load Balancer [NLB L4] (e.g. 10.10.10.10/22)
## IBM PowerVM:          the VIP must be within the VLAN Subnet range
## OVirt KVM:            the VIP must be within the VLAN Subnet range
## KubeVirt:             the VIP must be within the VLAN Subnet range
# sap_vm_provision_ha_vip_hana_primary: "ENTER_STRING_VALUE_HERE"

## Linux Pacemaker cluster setup for SAP - Cluster details
# sap_system_hana_cluster_name: 'clusterhdb'
# sap_system_hana_hacluster_user_password: 'clusterpass'
