---
# Ansible Playbook for SAP Web Dispatcher installation

# Use include_role / include_tasks inside Ansible Task block, instead of using roles declaration or Task block with import_roles.
# This ensures Ansible Roles, and the tasks within, will be parsed in sequence instead of parsing at Playbook initialisation.


#### Begin Infrastructure-as-Code provisioning ####

- name: Ansible Play to gather input for gathering vars and VM provisioning
  hosts: localhost
  gather_facts: false

  # pre_tasks used only for Interactive Prompts only and can be removed without impact
  pre_tasks:

    - name: Playbook Interactive - Check if standard execution with an Ansible Extravars file is requested by end user
      ansible.builtin.set_fact:
        playbook_enable_interactive_prompts: "{{ true if (sap_vm_provision_iac_type is undefined and sap_vm_provision_iac_platform is undefined) else false }}"

    - name: Playbook Interactive - Provision execution - Input for sap_vm_provision_iac_type
      ansible.builtin.pause:
        prompt: "Please choose Infrastructure-as-Code automation from list - ansible , ansible_to_terraform (for existing_hosts, use Ansible standard execution with an Ansible Extravars file)"
      register: sap_vm_provision_iac_type_register
      no_log: true
      when: playbook_enable_interactive_prompts

    - name: Playbook Interactive - Provision execution - Input for sap_vm_provision_iac_platform
      ansible.builtin.pause:
        prompt: "Please choose Infrastructure Platform from list - aws_ec2_vs , gcp_ce_vm , ibmcloud_powervs , ibmcloud_vs , ibmpowervm_vm , kubevirt_vm , msazure_vm , ovirt_vm"
      register: sap_vm_provision_iac_platform_register
      no_log: true
      when: playbook_enable_interactive_prompts

    - name: Playbook Interactive - SAP Deployment execution - Input for playbook_enable_default_vars_sap
      ansible.builtin.pause:
        prompt: "Please choose if defaults should be used for SAP Software installation (e.g. SAP System ID) - true , false"
      register: playbook_enable_default_vars_sap_register
      no_log: true
      when: playbook_enable_interactive_prompts

    - name: Playbook Interactive - Set facts from initial prompts
      ansible.builtin.set_fact:
        sap_vm_provision_iac_type: "{{ sap_vm_provision_iac_type_register.user_input }}"
        sap_vm_provision_iac_platform: "{{ sap_vm_provision_iac_platform_register.user_input }}"
        playbook_enable_default_vars_sap: "{{ playbook_enable_default_vars_sap_register.user_input }}"
      when: playbook_enable_interactive_prompts

    - name: Playbook Interactive - Trigger prompts for VM provisioning via Terraform
      ansible.builtin.include_tasks: interactive/ansible_tasks_control_inputs.yml
      when:
        - playbook_enable_interactive_prompts
        - sap_vm_provision_iac_type == "ansible_to_terraform"

    - name: Playbook Interactive - Trigger prompts for VM provisioning via Ansible
      ansible.builtin.include_tasks: interactive/ansible_tasks_control_inputs.yml
      when:
        - playbook_enable_interactive_prompts
        - sap_vm_provision_iac_type == "ansible"


#### Provision VM ####

- name: Ansible Play to create dynamic inventory group for provisioning
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create dynamic inventory group for Ansible Role sap_vm_provision
      ansible.builtin.add_host:
        name: "{{ item }}"
        group: sap_vm_provision_target_inventory_group
      loop: "{{ lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan].keys() }}"
      when: sap_vm_provision_iac_type == "ansible" or sap_vm_provision_iac_type == "ansible_to_terraform"

- name: Ansible Play to provision hosts for SAP
  hosts: sap_vm_provision_target_inventory_group # Ansible Play target hosts pattern, use Inventory Group created by previous Ansible Task (add_host)
  gather_facts: false
  tasks:

    - name: Execute Ansible Role sap_vm_provision
      ansible.builtin.include_role:
        name: community.sap_infrastructure.sap_vm_provision
      when: sap_vm_provision_iac_type == "ansible" or sap_vm_provision_iac_type == "ansible_to_terraform"


#### VM storage filesystem setup ####

- name: Ansible Play for hosts storage setup
  hosts: nwas_aas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    # Use inventory_hostname_short to retrieve host specification from the dictionary. While ansible_hostname will work for Ansible only, using Ansible>Terraform may see ansible_hostname as 'localhost' and fail
    - name: Execute Ansible Role sap_storage_setup
      ansible.builtin.include_role:
        name: community.sap_install.sap_storage_setup
      vars:
        sap_storage_setup_sid: "{{ host_specifications_dictionary[sap_vm_provision_host_specification_plan][inventory_hostname_short].sap_storage_setup_sid | default('') }}"
        sap_storage_setup_host_type: "{{ host_specifications_dictionary[sap_vm_provision_host_specification_plan][inventory_hostname_short].sap_storage_setup_host_type | list }}"
        # sap_storage_setup_definition set for the host by sap_vm_provision Ansible Role
      when:
        - sap_vm_provision_iac_type == "ansible" or sap_vm_provision_iac_type == "ansible_to_terraform"
        - not sap_vm_provision_iac_type == "existing_hosts"


# - name: Ansible Play to execute Preflight Checks
#   hosts: nwas_aas
#   become: true
#   any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
#   max_fail_percentage: 0
#   tasks:

#     - name: Execute Ansible Role sap_vm_preflight_checks
#       ansible.builtin.include_role:
#         name: community.sap_infrastructure.sap_vm_verify


#### Begin downloading SAP software installation media to hosts ####

- name: Ansible Play for preparing downloads of SAP Software installation media
  hosts: nwas_aas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Create directories if does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ sap_install_media_detect_source_directory }}"

    - name: Install Python package manager pip3 to system Python
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Ensure OS Packages for lxml are installed
      ansible.builtin.package:
        name:
          - python3-lxml
          - libxslt-devel
          - libxml2-devel
        state: present

    - name: Install Python dependency wheel to system Python
      ansible.builtin.pip:
        name:
          - wheel

    - name: Install Python dependencies for Ansible Modules to system Python
      ansible.builtin.pip:
        name:
          - urllib3
          - requests
          - beautifulsoup4
          - lxml



- name: Ansible Play for downloading SAP S/4HANA installation media
  hosts: nwas_aas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    # Set facts based on the install dictionary and the default template selected
    - name: Set fact x86_64 softwarecenter_search_list
      ansible.builtin.set_fact:
        softwarecenter_search_list: "{{ softwarecenter_search_list_x86_64[sap_playbook_webdispatcher_version] }}"
      when:
        - ansible_architecture == "x86_64"

    # Set facts based on the install dictionary and the default template selected
    - name: Set fact ppc64le softwarecenter_search_list
      ansible.builtin.set_fact:
        softwarecenter_search_list: "{{ softwarecenter_search_list_ppc64le[sap_playbook_webdispatcher_version] }}"
      when:
        - ansible_architecture == "ppc64le"

    - name: Execute Ansible Module with system Python to download installation media for SAP HANA and SAP NetWeaver for hosting SAP S/4HANA
      community.sap_launchpad.software_center_download:
        suser_id: "{{ sap_id_user }}"
        suser_password: "{{ sap_id_user_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ sap_install_media_detect_source_directory }}"
      loop: "{{ softwarecenter_search_list }}"
      loop_control:
        label: "{{ item }} : {{ download_task.msg }}"
      register: download_task
      retries: 1
      until: download_task is not failed



#### Begin SAP software hosts preparation ####

- name: Ansible Play for preparing all SAP software hosts
  hosts: nwas_aas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_general_preconfigure
      ansible.builtin.include_role:
        name: community.sap_install.sap_general_preconfigure

    - name: Execute Ansible Role sap_netweaver_preconfigure
      ansible.builtin.include_role:
        name: community.sap_install.sap_netweaver_preconfigure


#### Begin SAP software installations ####

- name: Ansible Play for SAP Web Dispatcher installation
  hosts: nwas_aas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: community.sap_install.sap_install_media_detect
      vars:
        sap_install_media_detect_swpm: true
        sap_install_media_detect_hostagent: true
        sap_install_media_detect_igs: true
        sap_install_media_detect_kernel: true
        sap_install_media_detect_webdisp: true

    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
