name: CodeSpell

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          # lowercase only
          ignore_words_list: aas,iterm,daa
